/*Inserção de produtos nas categorias*/
/*pessoa jurídica*/
insert into oferta (id_pessoa, data_oferta, titulo, texto, inicio_oferta, termino_oferta, preco_original, desconto,
					preco_atual, foto_nome_oferta, categoria, marca) values
('21', current_timestamp(), 'Teste', 'Teste teste teste', '2022-01-01', '2023-01-05', '90', '10',
						'80', '21_eletronicos.webp', 'eletronicos', 'Xiaomi');

/*('141', current_timestamp(), 'Teste', 'Teste teste teste', current_timestamp(), current_timestamp(), '90', '10',
						'80', '21_eletronicos.webp', 'eletronicos', 'Xiaomi'),
('142', current_timestamp(), 'Teste', 'Teste teste teste', current_timestamp(), current_timestamp(), '90', '10',
						'80', '22_eletronicos.webp', 'eletronicos', 'iPhone'),
('143', current_timestamp(), 'Teste', 'Teste teste teste', current_timestamp(), current_timestamp(), '90', '10',
						'80', '23_eletronicos.png', 'eletronicos', 'SAMSUNG'),
('144', current_timestamp(), 'Teste', 'Teste teste teste', current_timestamp(), current_timestamp(), '90', '10',
						'80', '24_eletronicos.webp', 'eletronicos', 'iPhone'),
('145', current_timestamp(), 'Teste', 'Teste teste teste', current_timestamp(), current_timestamp(), '90', '10',
						'80', '25_eletronicos.webp', 'eletronicos', 'Xiaomi'),
('146', current_timestamp(), 'Teste', 'Teste teste teste', current_timestamp(), current_timestamp(), '90', '10',
						'80', '26_eletronicos.webp', 'eletronicos', 'SAMSUNG'),
('147', current_timestamp(), 'Teste', 'Teste teste teste', current_timestamp(), current_timestamp(), '90', '10',
						'80', '27_eletronicos.webp', 'eletronicos', 'LG'),
('148', current_timestamp(), 'Teste', 'Teste teste teste', current_timestamp(), current_timestamp(), '90', '10',
						'80', '28_eletronicos.webp', 'eletronicos', 'LG'),
('149', current_timestamp(), 'Teste', 'Teste teste teste', current_timestamp(), current_timestamp(), '90', '10',
						'80', '29_eletronicos.webp', 'eletronicos', 'Poco'),
('150', current_timestamp(), 'Teste', 'Teste teste teste', current_timestamp(), current_timestamp(), '90', '10',
						'80', '30_eletronicos.png', 'eletronicos', 'Poco'),
('151', current_timestamp(), 'Teste', 'Teste teste teste', current_timestamp(), current_timestamp(), '90', '10',
						'80', '31_eletronicos.webp', 'eletronicos', 'SAMSUNG'),
('152', current_timestamp(), 'Teste', 'Teste teste teste', current_timestamp(), current_timestamp(), '90', '10',
						'80', '32_eletronicos.webp', 'eletronicos', 'SAMSUNG'),
('153', current_timestamp(), 'Teste', 'Teste teste teste', current_timestamp(), current_timestamp(), '90', '10',
						'80', '33_eletronicos.webp', 'eletronicos', 'SAMSUMG'),
('154', current_timestamp(), 'Teste', 'Teste teste teste', current_timestamp(), current_timestamp(), '90', '10',
						'80', '34_eletronicos.webp', 'eletronicos', 'LG'),
('155', current_timestamp(), 'Teste', 'Teste teste teste', current_timestamp(), current_timestamp(), '90', '10',
						'80', '35_eletronicos.webp', 'eletronicos', 'LG'),
('156', current_timestamp(), 'Teste', 'Teste teste teste', current_timestamp(), current_timestamp(), '90', '10',
						'80', '36_eletronicos.webp', 'eletronicos', 'LG'),
('157', current_timestamp(), 'Teste', 'Teste teste teste', current_timestamp(), current_timestamp(), '90', '10',
						'80', '37_eletronicos.webp', 'eletronicos', 'SAMSUMG'),
('158', current_timestamp(), 'Teste', 'Teste teste teste', current_timestamp(), current_timestamp(), '90', '10',
						'80', '38_eletronicos.png', 'eletronicos', 'SAMSUNG'),
('159', current_timestamp(), 'Teste', 'Teste teste teste', current_timestamp(), current_timestamp(), '90', '10',
						'80', '39_eletronicos.png', 'eletronicos', 'Lenovo'),
('150', current_timestamp(), 'Teste', 'Teste teste teste', current_timestamp(), current_timestamp(), '90', '10',
						'80', '40_eletronicos.webp', 'eletronicos', 'Lenovo');*/