/*Inserção de produtos nas categorias*/
/*pessoa jurídica*/
insert into oferta (id_pessoa, data_oferta, titulo, texto, inicio_oferta, termino_oferta, preco_original, desconto,
						preco_atual, foto_nome_oferta, categoria, marca) values
('21', current_timestamp(), 'Teste', 'Teste teste teste', current_timestamp(), current_timestamp(), '90', '10',
						'80', '21_eletronicos.webp', 'eletronicos', 'Xiaomi'),
('22', current_timestamp(), 'Teste', 'Teste teste teste', current_timestamp(), current_timestamp(), '90', '10',
						'80', '22_eletronicos.webp', 'eletronicos', 'iPhone'),
('23', current_timestamp(), 'Teste', 'Teste teste teste', current_timestamp(), current_timestamp(), '90', '10',
						'80', '23_eletronicos.png', 'eletronicos', 'SAMSUNG'),
('24', current_timestamp(), 'Teste', 'Teste teste teste', current_timestamp(), current_timestamp(), '90', '10',
						'80', '24_eletronicos.webp', 'eletronicos', 'iPhone'),
('25', current_timestamp(), 'Teste', 'Teste teste teste', current_timestamp(), current_timestamp(), '90', '10',
						'80', '25_eletronicos.webp', 'eletronicos', 'Xiaomi'),
('26', current_timestamp(), 'Teste', 'Teste teste teste', current_timestamp(), current_timestamp(), '90', '10',
						'80', '26_eletronicos.webp', 'eletronicos', 'SAMSUNG'),
('27', current_timestamp(), 'Teste', 'Teste teste teste', current_timestamp(), current_timestamp(), '90', '10',
						'80', '27_eletronicos.webp', 'eletronicos', 'LG'),
('28', current_timestamp(), 'Teste', 'Teste teste teste', current_timestamp(), current_timestamp(), '90', '10',
						'80', '28_eletronicos.webp', 'eletronicos', 'LG'),
('29', current_timestamp(), 'Teste', 'Teste teste teste', current_timestamp(), current_timestamp(), '90', '10',
						'80', '29_eletronicos.webp', 'eletronicos', 'Poco'),
('30', current_timestamp(), 'Teste', 'Teste teste teste', current_timestamp(), current_timestamp(), '90', '10',
						'80', '30_eletronicos.png', 'eletronicos', 'Poco'),
('31', current_timestamp(), 'Teste', 'Teste teste teste', current_timestamp(), current_timestamp(), '90', '10',
						'80', '31_eletronicos.webp', 'eletronicos', 'SAMSUNG'),
('32', current_timestamp(), 'Teste', 'Teste teste teste', current_timestamp(), current_timestamp(), '90', '10',
						'80', '32_eletronicos.webp', 'eletronicos', 'SAMSUNG'),
('33', current_timestamp(), 'Teste', 'Teste teste teste', current_timestamp(), current_timestamp(), '90', '10',
						'80', '33_eletronicos.webp', 'eletronicos', 'SAMSUMG'),
('34', current_timestamp(), 'Teste', 'Teste teste teste', current_timestamp(), current_timestamp(), '90', '10',
						'80', '34_eletronicos.webp', 'eletronicos', 'LG'),
('35', current_timestamp(), 'Teste', 'Teste teste teste', current_timestamp(), current_timestamp(), '90', '10',
						'80', '35_eletronicos.webp', 'eletronicos', 'LG'),
('36', current_timestamp(), 'Teste', 'Teste teste teste', current_timestamp(), current_timestamp(), '90', '10',
						'80', '36_eletronicos.webp', 'eletronicos', 'LG'),
('37', current_timestamp(), 'Teste', 'Teste teste teste', current_timestamp(), current_timestamp(), '90', '10',
						'80', '37_eletronicos.webp', 'eletronicos', 'SAMSUMG'),
('38', current_timestamp(), 'Teste', 'Teste teste teste', current_timestamp(), current_timestamp(), '90', '10',
						'80', '38_eletronicos.png', 'eletronicos', 'SAMSUNG'),
('39', current_timestamp(), 'Teste', 'Teste teste teste', current_timestamp(), current_timestamp(), '90', '10',
						'80', '39_eletronicos.png', 'eletronicos', 'Lenovo'),
('40', current_timestamp(), 'Teste', 'Teste teste teste', current_timestamp(), current_timestamp(), '90', '10',
						'80', '40_eletronicos.webp', 'eletronicos', 'Lenovo'); 